spring.application.name=telemedicine

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_EMAIL_USERNAME}
spring.mail.password=${SPRING_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000

#change to 3000
app.cors.allowed-origins=http://localhost:5173

app.article.storage-path=/mediroh/articles